%YAML:1.0

OptiTrack.TrackBack: 1
OptiTrack.TrackBackPixelErr: 20
OptiTrack.MaxPoints: 200
OptiTrack.MinDist: 20
OptiTrack.QualityLevel: 0.03
OptiTrack.PyramidLevel: 3
OptiTrack.Iterations: 20
OptiTrack.EPS: 0.01
OptiTrack.ShowTrackFrames: 5

Init.MinDisparity: 8
Init.MinMatchedFeatNum: 20
Init.ReprojectErr: 1
Init.HomographyTransformErr: 3

PnpSolver.ReprojectErr: 6.0
PnpSolver.SuccessRatio: 0.7
PnpSolver.ShowDebugInfo: 1

Sim.Length.x: 10.0
Sim.Length.y: 10.0
Sim.Length.z: 0.01
Sim.Origin.x: 0.0
Sim.Origin.y: 0.0
Sim.Origin.z: 1.0
Sim.FeatureSize: 1000

Camera.Intrinisic: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [3.8380740012211299e+02, 0., 3.2390419598611703e+02, 
         0., 3.8417089869351622e+02, 2.3849409892824440e+02, 
         0., 0., 1. ]
Camera.Distortion: !!opencv-matrix
  rows: 1
  cols: 4
  dt: d
  data: [1.4136305444704679e-02, -2.9516089910934715e-02,1.0711762333815588e-04, 8.7513871102637506e-04]
Camera.IsFisheye : 0
Camera.Width: 640
Camera.Height: 480