%YAML:1.0

OptiTrack.TrackBack: 0
OptiTrack.MaxPoints: 120
OptiTrack.MinDist: 20
OptiTrack.QualityLevel: 0.03
OptiTrack.PyramidLevel: 3
OptiTrack.Iterations: 20
OptiTrack.EPS: 0.01


Init.MinDisparity: 8
Init.MinMatchedFeatNum: 20
Init.ReprojectErr: 1
Init.HomographyTransformErr: 3

Sim.Length.x: 1.0
Sim.Length.y: 1.0
Sim.Length.z: 0.2
Sim.Origin.x: 1.0
Sim.Origin.y: 1.0
Sim.Origin.z: 0.0
Sim.FeatureSize: 20

Camera.Intrinisic: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [171.9127719, 0.0, 166.9005009,
           0.0, 172.2210894, 117.5154348, 
           0.0,  0.0,   1.0]
Camera.Distortion: !!opencv-matrix
  rows: 1
  cols: 4
  dt: d
  data: [0.2742372,-0.3608315,0.1168417,0.0000000]
Camera.IsFisheye : 1
Camera.Width: 320
Camera.Height: 240