%YAML:1.0

#common parameters
imu_topic: "/imu0"
image_topic: "/cam0/image_raw"
replay_folder: "/home/kdq/Workspace/ZeroZero/Log/test/20201106/gross_test/rovio.replay"
output_path: "/home/kdq/Workspace/ZeroZero/Log/test/20201106/gross_test/"
skip_time: 10.0
write_bag: 1
speed_k: 1.0
