%YAML:1.0
---
imuFreq: 200
imageFreq: 30
simStart: 0
simEnd: 20
noise:
  gyro_meas_sigma: 0.0001
  acc_meas_sigma: 0.001
  gyro_bias_sigma: 0.00001
  acc_bias_sigma: 0.0001
  pixel_sigma: 2


  
Tbc: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  data: [1.0, 0., 0., 0.,
         0.0,1.0, 0.,0.1,
          0., 0.,1.0,0.2,
          0., 0., 0., 1.]

