%YAML:1.0

Estimator.KeyFrameMatchedPoints: 20
Estimator.KeyFrameParallexThreshold: 5
Estimator.ReprojectPixelErr: 3
Estimator.BundleAdjustment: 1
Estimator.EnableFeaturePrediction: 0
Estimator.EnableVOAlignedToWorld: 0

OptiTrack.TrackBack: 1
OptiTrack.TrackBackPixelErr: 1.0
OptiTrack.MaxPoints: 120
OptiTrack.MinDist: 15
OptiTrack.QualityLevel: 0.03
OptiTrack.PyramidLevel: 2
OptiTrack.Iterations: 10
OptiTrack.EPS: 0.01
OptiTrack.PredictEnable: 0
OptiTrack.ShowTrackFrames: 2
OptiTrack.ShowDebugInfos: 0

Init.MinDisparity: 20
Init.MinMatchedFeatNum: 40
Init.ReprojectErr: 1
Init.HomographyTransformErr: 3

PnpSolver.ReprojectErr: 6.0
PnpSolver.SuccessRatio: 0.5
PnpSolver.ShowDebugInfo: 0

Sim.Length.x: 10.0
Sim.Length.y: 10.0
Sim.Length.z: 0.01
Sim.Origin.x: 0.0
Sim.Origin.y: 0.0
Sim.Origin.z: 1.0
Sim.FeatureSize: 2000

#d435i parameters
stereo.stream: 0
stereo.width: 640
stereo.height: 480
stereo.frame_rate: 90
stereo.auto_exposure: 1
stereo.exposure_time: 500
stereo.exposure_gain: 100
stereo.ae_point: 1500
Camera.Intrinisic: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [3.8380740012211299e+02, 0., 3.2390419598611703e+02, 
         0., 3.8417089869351622e+02, 2.3849409892824440e+02, 
         0., 0., 1. ]
Camera.Distortion: !!opencv-matrix
  rows: 1
  cols: 4
  dt: d
  data: [1.4136305444704679e-02, -2.9516089910934715e-02,1.0711762333815588e-04, 8.7513871102637506e-04]
Camera.IsFisheye : 0
Camera.Width: 640
Camera.Height: 480

Rbc: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [1.0, 0.0, 0.0,
         0.0, 1.0, 0.0,
         0.0, 0.0, 1.0]
tbc: !!opencv-matrix
  rows: 3
  cols: 1
  dt: d
  data: [0.02, 0.04, 0.005]